import Link from "next/link"
import styles from "./header.module.css"

const links = [{
    label: 'Home',
    route: '/'
}, {
    label: 'About Me',
    route: '/about_me'
}, {
    label: 'Curriculum vitae',
    route: '/cv'
}, {
    label: 'Portfolio',
    route: '/portfolio'
}, {
    label: 'Contact',
    route: '/contact'
}]
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export function Header() {
    return (
        <header className={styles.header}>
            <nav>
                <ul className={styles.navigation}>
                    {links.map(({ label, route }) => (
                        <li key={route}>
                            <Link href={route}>
                                {label}
                            </Link>
                        </li>
                    ))}
                </ul>
            </nav>
        </header>
    )
}