import Link from 'next/link'
import styles from './header.module.css'

const links = [{
  label: 'Home',
  route: '/'
}, {
  label: 'About',
  route: '/about'
}, {
  label: 'Curriculum vitae',
  route: '/cv'
}, {
  label: 'Projects',
  route: '/projects'
}, {
  label: 'Contact',
  route: '/contact'
}]
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export function Header () {
  return (
    <header className={styles.header}>
      <nav className={styles.navigation}>
        <ul className={styles.list}>
          {links.map(({ label, route }) => (
            <li key={route}>
              <Link href={route}>
                {label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  )
}
